// design/build-gallery.mjs
//
// Generates two mechanically-derived artifacts from design/tokens.mjs, the
// single source of truth:
//   - design/tokens.generated.css — every token as a CSS custom property
//     (color tokens scoped per `[data-theme]` panel so both themes can be on
//     screen at once), plus a handful of `--gallery-chrome-*` constants used
//     only by the gallery page's own layout (explicitly NOT DeckTech design
//     tokens — kept out of design/tokens.mjs on purpose).
//   - design/gallery.html — the viewable gallery. It contains ZERO hardcoded
//     color/radius/duration literals of its own: every style declaration is
//     `var(--dt-*)` or `var(--gallery-chrome-*)`. This is deliberate: the
//     gallery is itself a "new surface" per Phase 6 success criterion 1, and
//     test/design-tokens.test.mjs lints it exactly like any future DeckTech
//     UI surface.
//
// Run with: node design/build-gallery.mjs
// Both outputs are committed so the gallery is viewable without a build step.

import { writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import path from "node:path";
import { COLOR_TOKENS, NON_COLOR_TOKENS } from "./tokens.mjs";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const CSS_OUTPUT_PATH = path.join(__dirname, "tokens.generated.css");
const HTML_OUTPUT_PATH = path.join(__dirname, "gallery.html");

function escapeHtml(str) {
  return String(str)
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}

// Gallery-tool-only presentation constants. Not DeckTech design tokens —
// kept out of design/tokens.mjs so they can never be mistaken for one, but
// still generated (not hand-authored) so they stay out of the surface lint
// the same way design/tokens.mjs does.
const CHROME_VARS = {
  "--gallery-chrome-page-bg": "#efefef",
  "--gallery-chrome-text": "#111111",
  "--gallery-chrome-lede": "#444444",
  "--gallery-chrome-card-bg": "rgba(127,127,127,.08)",
  "--gallery-chrome-border": "#dddddd",
  "--gallery-chrome-badge-bg": "#dddddd",
  "--gallery-chrome-swatch-base": "#808080",
  "--gallery-chrome-source": "#555555",
  "--gallery-chrome-pill-radius": "999px",
};

// Theme-scoped so the warning color keeps AA-ish contrast against BOTH the
// near-black dark panel and the near-white light panel, instead of one fixed
// hex compromising on both (the low-contrast-text finding this file was
// reviewed against).
const CHROME_CAVEAT_BY_THEME = {
  dark: "#ffb37a", // light amber on a near-black canvas
  light: "#7a3900", // burnt-amber on a near-white canvas
};

// ---------------------------------------------------------------------------
// design/tokens.generated.css
// ---------------------------------------------------------------------------

const nonColorCss = NON_COLOR_TOKENS.map((t) => `  ${t.name}: ${t.value};`).join("\n");
const chromeCss = Object.entries(CHROME_VARS)
  .map(([k, v]) => `  ${k}: ${v};`)
  .join("\n");

function themeColorCss(theme) {
  const tokenLines = COLOR_TOKENS.map((t) => `  ${t.name}: ${t[theme].value};`).join("\n");
  return `${tokenLines}\n  --gallery-chrome-caveat: ${CHROME_CAVEAT_BY_THEME[theme]};`;
}

const css = `/* AUTO-GENERATED by design/build-gallery.mjs from design/tokens.mjs.
   Do not hand-edit — this file IS the token source in CSS form, mechanically
   derived, and is allowlisted from the hardcoded-literal lint the same way
   design/tokens.mjs is (see test/design-tokens.test.mjs ALLOWLISTED_FILES). */

:root {
${nonColorCss}
${chromeCss}
}

[data-theme="dark"] {
${themeColorCss("dark")}
}

[data-theme="light"] {
${themeColorCss("light")}
}
`;

writeFileSync(CSS_OUTPUT_PATH, css, "utf8");

// ---------------------------------------------------------------------------
// design/gallery.html
// ---------------------------------------------------------------------------

function colorSwatch(t, theme) {
  const val = t[theme];
  const provenance =
    theme === "dark" ? `source: ${escapeHtml(val.source)}` : `basis: ${escapeHtml(val.basis)}`;
  const caveat = val.caveat ? `<p class="caveat">${escapeHtml(val.caveat)}</p>` : "";
  const isShadowLike = /^(inset\s|0\s)/.test(val.value);
  const swatchStyle = isShadowLike
    ? `box-shadow: var(${t.name});`
    : `background: var(${t.name});`;
  return `
      <div class="swatch" data-token="${escapeHtml(t.name)}" data-theme="${theme}">
        <div class="swatch-preview" style="${swatchStyle}"></div>
        <div class="swatch-meta">
          <code class="swatch-name">${escapeHtml(t.name)}</code>
          <code class="swatch-value">${escapeHtml(val.value)}</code>
          <p class="swatch-source">${provenance}</p>
          ${caveat}
        </div>
      </div>`;
}

function nonColorRow(t) {
  return `
      <tr>
        <td><code>${escapeHtml(t.name)}</code></td>
        <td><span class="kind-badge">${escapeHtml(t.kind)}</span></td>
        <td><code>${escapeHtml(t.value)}</code></td>
        <td class="source-cell">${escapeHtml(t.source)}</td>
      </tr>`;
}

const html = `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8" />
<title>DeckTech design tokens</title>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link rel="stylesheet" href="tokens.generated.css" />
<style>
  * { box-sizing: border-box; }

  body {
    margin: 0;
    padding: var(--dt-s-11);
    font-family: var(--dt-font-ui);
    background: var(--gallery-chrome-page-bg);
    color: var(--gallery-chrome-text);
  }

  h1 { font-family: var(--dt-font-display); margin: 0 0 var(--dt-s-3); }
  p.lede { max-width: 72ch; color: var(--gallery-chrome-lede); }

  .panels {
    display: grid;
    grid-template-columns: 1fr 1fr;
    gap: var(--dt-s-11);
    margin-top: var(--dt-s-11);
  }
  @media (max-width: 900px) {
    .panels { grid-template-columns: 1fr; }
  }

  .theme-panel {
    border-radius: var(--dt-r-modal);
    padding: var(--dt-s-11);
    overflow: hidden;
    background: var(--dt-canvas);
    color: var(--dt-ink);
  }

  .theme-panel h2 {
    font-family: var(--dt-font-display);
    margin: 0 0 var(--dt-s-9);
    text-transform: uppercase;
    letter-spacing: .04em;
    font-size: 13px;
    opacity: .7;
  }

  .swatch-grid {
    display: grid;
    grid-template-columns: repeat(auto-fill, minmax(180px, 1fr));
    gap: var(--dt-s-7);
  }

  .swatch {
    border-radius: var(--dt-r-control);
    overflow: hidden;
    background: var(--gallery-chrome-card-bg);
  }
  .swatch-preview {
    height: 64px;
    border-radius: var(--dt-r-control) var(--dt-r-control) 0 0;
    background-color: var(--gallery-chrome-swatch-base);
  }
  .swatch-meta { padding: var(--dt-s-4); }
  .swatch-name { display: block; font-size: 13px; font-weight: 600; color: var(--dt-ink); word-break: break-all; }
  .swatch-value { display: block; font-size: 12px; color: var(--dt-ink-2); word-break: break-all; margin-top: 2px; }
  .swatch-source { font-size: 12px; color: var(--dt-ink-3); margin: var(--dt-s-1) 0 0; line-height: 1.4; }
  .caveat { font-size: 12px; font-weight: 600; color: var(--gallery-chrome-caveat); margin: var(--dt-s-1) 0 0; line-height: 1.4; }

  section.non-color { margin-top: var(--dt-s-14); }
  table { width: 100%; border-collapse: collapse; font-size: 12px; }
  th, td {
    text-align: left;
    padding: var(--dt-s-2) var(--dt-s-4);
    border-bottom: 1px solid var(--gallery-chrome-border);
    vertical-align: top;
  }
  .kind-badge {
    display: inline-block;
    padding: 1px 6px;
    border-radius: var(--gallery-chrome-pill-radius);
    background: var(--gallery-chrome-badge-bg);
    font-size: 12px;
    text-transform: uppercase;
    letter-spacing: .03em;
  }
  .source-cell { font-size: 12px; color: var(--gallery-chrome-source); }
</style>
</head>
<body>
  <h1>DeckTech design tokens</h1>
  <p class="lede">
    Generated by <code>design/build-gallery.mjs</code> from <code>design/tokens.mjs</code> —
    the single source of truth (DES-01/DES-02, Phase 6). ${COLOR_TOKENS.length} color tokens,
    each with a transcribed dark value and an authored light value (D11); both themes render
    side by side below, never as a toggle. ${NON_COLOR_TOKENS.length} non-color tokens
    (radius, spacing, motion, type) follow.
  </p>

  <div class="panels">
    <div class="theme-panel" data-theme="dark">
      <h2>Dark (transcribed)</h2>
      <div class="swatch-grid">
${COLOR_TOKENS.map((t) => colorSwatch(t, "dark")).join("\n")}
      </div>
    </div>
    <div class="theme-panel" data-theme="light">
      <h2>Light (authored — DES-02 / D11)</h2>
      <div class="swatch-grid">
${COLOR_TOKENS.map((t) => colorSwatch(t, "light")).join("\n")}
      </div>
    </div>
  </div>

  <section class="non-color">
    <h2>Geometry, motion &amp; type (theme-independent)</h2>
    <table>
      <thead><tr><th>Token</th><th>Kind</th><th>Value</th><th>Source</th></tr></thead>
      <tbody>
${NON_COLOR_TOKENS.map(nonColorRow).join("\n")}
      </tbody>
    </table>
  </section>
</body>
</html>
`;

writeFileSync(HTML_OUTPUT_PATH, html, "utf8");
console.log(
  `wrote ${CSS_OUTPUT_PATH} and ${HTML_OUTPUT_PATH} (${COLOR_TOKENS.length} color + ${NON_COLOR_TOKENS.length} non-color tokens)`,
);
